language: go

go_import_path: github.com/src-d/gitbase

matrix:
  fast_finish: true
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-6
    - g++-6
    - libonig-dev


before_install:
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 90
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-6 90

before_script:
  - docker run -d --name bblfshd --privileged -p 9432:9432 -v /var/lib/bblfshd:/var/lib/bblfshd bblfsh/bblfshd
  - docker exec -it bblfshd bblfshctl driver install python bblfsh/python-driver
  - docker exec -it bblfshd bblfshctl driver install php bblfsh/php-driver
  - docker exec -it bblfshd bblfshctl driver install go bblfsh/go-driver
  - go get -v github.com/go-sql-driver/mysql/...
  - go get gopkg.in/src-d/go-git-fixtures.v3/...

script:
  - make test-coverage codecov
  - make ci-e2e

jobs:
  include:
    - go: 1.11.x
      os: linux
      sudo: required
      dist: trusty
      services: [docker]

      before_deploy:
        - make docker-push-latest-release
        - make static-package

      deploy:
        provider: releases
        api_key: $GITHUB_TOKEN
        file_glob: true
        file: build/*linux_amd64.tar.gz
        skip_cleanup: true
        on:
          tags: true

    - go: 1.11.x
      os: osx
      osx_image: xcode9.3

      before_install:
        - echo "skipping before_install for macOS"

      before_script:
        - echo "skipping before_script for macOS"

      script:
        - brew update
        - brew install oniguruma
        - make packages || echo "" # will fail because of docker being missing
        - if [ ! -f "build/gitbase_darwin_amd64/gitbase" ]; then echo "gitbase binary not generated" && exit 1; fi
        - cd build
        - tar -cvzf "gitbase_${TRAVIS_TAG}_darwin_amd64.tar.gz" gitbase_darwin_amd64
        - cd ..

      deploy:
        provider: releases
        api_key: $GITHUB_TOKEN
        file_glob: true
        file: build/*darwin_amd64.tar.gz
        skip_cleanup: true
        on:
          tags: true
